services:
  - type: web
    name: code-executor-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist

  - type: web
    name: code-executor-server
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    plan: free
